require '../common/db/kloy/KloyDb.rb'

class PromoQueryes < KloyDb

  def initStatements()

  end

  def cleanByHostId pHostId
    DB_CONN.do("DELETE FROM WDPPRM_ACM_COND WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM WDPPRM_COND WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM WDPPRM_GEN_COND WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM WDPPRM_HEAD WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM WDPPRM_RULE WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM WDPPRM_RULE_ITM WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    #DB_CONN.do("DELETE FROM WDPPRM_SUPP WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM OPROMO_ACM_COND WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM OPROMO_CHECK WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM OPROMO_COND WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM OPROMO_DPL WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    #DB_CONN.do("DELETE FROM OPROMO_EXCP WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM OPROMO_GEN_COND WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM OPROMO_HEAD WHERE ID_PROMO_OFF IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM OPROMO_NODE WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM OPROMO_RULE WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM OPROMO_RULE_ITM WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM OPROMO_SPC_ITM WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM OPROMO_SPECIAL WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    #DB_CONN.do("DELETE FROM WPROMO_IMPT WHERE ID_PROMO_OFF_FK IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.do("DELETE FROM OPROMO_OFF WHERE ID_PROMO_OFF IN (SELECT ID_PROMO_OFF FROM OPROMO_OFF WHERE PROMO_HOST_ID = \'#{pHostId}\' )")
    DB_CONN.commit
  end


  def closeStatements()

  end

end