lab_ravenna_development:
   authServiceUrl: 192.168.202.250/auth.php
   kwlServletUrl: 192.168.91.83:8080/KwlServlet/KwlServlet
   kwlUtilServletUrl: 192.168.91:83:8081/KwlUtilServlet/KwlUtilServlet
   ekoLoyServletUrl: 192.168.91.83:8080/EkoLoyServlet/EkoLoyServlet
   LoyaltyWsUrl: http://192.168.91.83:85/LoyaltyWsSSL/manager.asmx?wsdl
   kStoreServletUrl: 192.168.202.222:9080/kStore/SelfScan
   debugSteps: false
   Vs5ServerIp: 192.168.202.63
   Vs5KloySvcPort: "3099"

lab_ravenna_showcase:
   authServiceUrl: 192.168.202.250/auth.php
   kwlServletUrl: 192.168.202.68:8081/KwlServlet/KwlServlet
   kwlUtilServletUrl: 192.168.202.68:8081/KwlUtilServlet/KwlUtilServlet
   ekoLoyServletUrl: 192.168.202.68:8081/EkoLoyServlet/EkoLoyServlet
   LoyaltyWsUrl: http://192.168.91.83:85/LoyaltyWsSSL/manager.asmx?wsdl
   kStoreServletUrl: 192.168.202.68:9080/kStore/SelfScan
   debugSteps: false
   Vs5ServerIp: 192.168.202.63
   Vs5KloySvcPort: "3099"

lab_ravenna_serverci:
   authServiceUrl: 192.168.202.250/auth_internal_test.php
   kwlServletUrl: 192.168.202.222:8081/KwlServlet/KwlServlet
   kwlUtilServletUrl: 192.168.202.222:8081/KwlUtilServlet/KwlUtilServlet
   ekoLoyServletUrl: 192.168.202.222:8081/EkoLoyServlet/EkoLoyServlet
   LoyaltyWsUrl: http://192.168.91.83:85/LoyaltyWsSSL/manager.asmx?wsdl
   kStoreServletUrl: 192.168.202.222:9080/kStore/SelfScan
   debugSteps: false
   Vs5ServerIp: 192.168.202.63
   Vs5KloySvcPort: "3099"

lab_ravenna_staging:
   authServiceUrl: 192.168.202.250/auth_internal_test.php
   kwlServletUrl: 192.168.202.222:8082/KwlServlet/KwlServlet
   kwlUtilServletUrl: 192.168.202.222:8082/KwlUtilServlet/KwlUtilServlet
   ekoLoyServletUrl: 192.168.202.222:8082/EkoLoyServlet/EkoLoyServlet
   LoyaltyWsUrl: http://192.168.91.83:85/LoyaltyWsSSL/manager.asmx?wsdl
   kStoreServletUrl: 192.168.202.68:9081/kStore/SelfScan
   #kStoreServletUrl: 192.168.202.69:8085/kStore/SelfScan
   debugSteps: false
   Vs5ServerIp: 192.168.202.63
   Vs5KloySvcPort: "3099"

lab_ingiro_ibm:
   authServiceUrl: 192.168.1.68:88/auth.php
   kwlServletUrl: 192.168.1.68:8081/KwlServlet/KwlServlet
   kwlUtilServletUrl: 192.168.1.68:8081/KwlUtilServlet/KwlUtilServlet
   ekoLoyServletUrl: 192.168.1.68:8081/EkoLoyServlet/EkoLoyServlet
   LoyaltyWsUrl: http://192.168.91.83:85/LoyaltyWsSSL/manager.asmx?wsdl
   kStoreServletUrl: 192.168.1.68:9081/kStore/SelfScan
   #kStoreServletUrl: 192.168.202.69:8085/kStore/SelfScan
   debugSteps: false
   Vs5ServerIp: 192.168.202.63
   Vs5KloySvcPort: "3099"

local:
   authServiceUrl: 192.168.1.68:88/auth.php
   kwlServletUrl: 192.168.1.68:8081/KwlServlet/KwlServlet
   kwlUtilServletUrl: 192.168.1.68:8081/KwlUtilServlet/KwlUtilServlet
   ekoLoyServletUrl: 192.168.1.68:8081/EkoLoyServlet/EkoLoyServlet
   LoyaltyWsUrl: http://192.168.91.83:85/LoyaltyWsSSL/manager.asmx?wsdl
   kStoreServletUrl: 127.0.0.1:9081/kStore/SelfScan
   #kStoreServletUrl: 192.168.202.69:8085/kStore/SelfScan
   debugSteps: false
   Vs5ServerIp: 192.168.202.63
   Vs5KloySvcPort: "3099"

ovh:
   authServiceUrl: 192.168.1.68:88/auth.php
   kwlServletUrl: 192.168.1.68:8081/KwlServlet/KwlServlet
   kwlUtilServletUrl: 192.168.1.68:8081/KwlUtilServlet/KwlUtilServlet
   ekoLoyServletUrl: 192.168.1.68:8081/EkoLoyServlet/EkoLoyServlet
   LoyaltyWsUrl: http://192.168.91.83:85/LoyaltyWsSSL/manager.asmx?wsdl
   kStoreServletUrl: 37.187.85.59:9081/kStore/SelfScan
   #kStoreServletUrl: 192.168.202.69:8085/kStore/SelfScan
   debugSteps: false
   Vs5ServerIp: 192.168.202.63
   Vs5KloySvcPort: "3099"

vbox:
   authServiceUrl: 192.168.1.68:88/auth.php
   kwlServletUrl: 192.168.1.68:8081/KwlServlet/KwlServlet
   kwlUtilServletUrl: 192.168.1.68:8081/KwlUtilServlet/KwlUtilServlet
   ekoLoyServletUrl: 192.168.1.68:8081/EkoLoyServlet/EkoLoyServlet
   LoyaltyWsUrl: http://192.168.91.83:85/LoyaltyWsSSL/manager.asmx?wsdl
   kStoreServletUrl: 192.168.1.134:9081/kStore/SelfScan
   #kStoreServletUrl: 10.15.18.133:9081/kStore/SelfScan
   #kStoreServletUrl: 192.168.202.69:8085/kStore/SelfScan
   debugSteps: false
   Vs5ServerIp: 192.168.202.63
   Vs5KloySvcPort: "3099"
